### ISSUE TITLE
No maps are showing

### ISSUE THREAD

**Issue by Tomkrulz** [dark-c0de/DarkLoader#4]
When I launch Darkloader, I get this error message:
![picture1](https://cloud.githubusercontent.com/assets/13504509/8892757/50a9c1b2-3331-11e5-89f1-7381b8640b38.png)
and when i press continue, there are no maps to select on the left:
![darkerror2](https://cloud.githubusercontent.com/assets/13504509/8892759/7ffc8c60-3331-11e5-9b79-a2f6d19cc71b.png)

**Comment by dark-c0de** [comment]
What version of Halo Online are you on? Can you show the "Details" section please?

Thanks

**Comment by Tomkrulz** [comment]
Version: 0.4.9.0

Details Section: http://pastebin.com/TQhGuqMe

**Comment by dark-c0de** [comment]
Hmm, i'm still not quite sure what's causing it. 0.4.9.0 isn't a version of Halo Online, it's a Eldewrito Version. That means you're probably on the 1.106708_cert_ms23___release. 

Maybe try installing halo to C:\halo\ and report back if that fixed your problem?
