### ISSUE TITLE
[FIXED] DarkLoader doesn't Work while Playing Online

### ISSUE THREAD

**Issue by TheWeion** [dark-c0de/DarkLoader#5]
I get a "Frost Error -1507" when I try to use DL online.

**Comment by sabaudaniel** [comment]
Same issue as the guy above. I'm guessing you just haven't updated it for the new patch?

**Comment by KingKoopa94** [comment]
Same issue :(
I even tried loading Halo Online regularly so the Frost Security loads then launching the game again but still get the same error.

**Comment by TheWeion** [comment]
This issue has been resolved: https://www.reddit.com/r/HaloOnline/comments/3nfd17/halo_online_offical_english_patch_always_works/

**Comment by KingKoopa94** [comment]
I wouldn't quite call this resolved.. More of a temporary way to use it for now (I hope..)
